### ISSUE TITLE
Enable Font Awesome icons

### ISSUE THREAD

**Issue by paulvickers** [asciidoctor/asciidoctor-pdf#15]
The PDF uses text tags instead of fontawesome icons for admonitions, even if you add `-a icons=font` to the command line. Any hints?

**Comment by wimdeblauwe** [comment]
+1

**Comment by jessedoyle** [comment]
Hi guys, I submitted pull request #90 that implements icon-based admonitions. Feel free to use it as a starting point!

**Comment by mojavelinux** [comment]
Thanks @jessedoyle! I'm hoping I'll be able to look at this soon.

**Comment by jessedoyle** [comment]
Awesome @mojavelinux! I'm going to be away for a couple of weeks so leave me a message if you have questions or concerns. I'll get to it as soon as I get back.

**Comment by mojavelinux** [comment]
:+1: Thanks for getting the ball rolling!

**Comment by mojavelinux** [comment]
Thanks to @jessedoyle, this is now resolved.

As a follow-up, I'd like to make the icons names and colors optionally part of the theme. This is clearly something people are going to want to customize. I've filed an issue to track this improvement. See #121.

**Comment by sagarbehere** [comment]
@mojavelinux could you explain how to use this feature? 

I just installed asciidoctor 1.5.2 along with asciidoctor-pdf 1.5.0.alpha.9, whose lib/asciidoctor-pdf/converter.rb seems to have the lines associated with commit 7463621 that fixes the issue.

However, I still don't see icons for admonitions. Perhaps I need to install the right fonts (font awesome?) How do I install it such that asciidoctor-pdf will just pick up the font and work? I could not find any documentation on this :(

**Comment by mojavelinux** [comment]
You shouldn't need to do anything special to enable this. As you've figured out, the prawn-icon gem provides and loads the necessary fonts.

Can you try to generate the examples/chronicles-example.adoc document in the repository and see if icons work there. That will tell us whether it's an issue with your environment or your document.

**Comment by sagarbehere** [comment]
@mojavelinux Thanks for the prompt response. It works now.

The issue was that I'm very new to asciidoctor and didn't realize that there should be :icons: font at the top of the document. When I added that, it works :)

**Comment by mojavelinux** [comment]
:+1:
