### ISSUE TITLE
Table cell that is white should be white not transparent

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#216]
The latest asciidoctor-pdf dev shows white table cells as transparent instead of white. Normally this would be fine, however, if you have a watermark background such as 'draft' it looks odd. Alpha currently does this correctly in my opinion. 

Output of dev:

![selection_230](https://cloud.githubusercontent.com/assets/8877333/8295886/cadce41a-190e-11e5-9e63-d2e36670c482.png)

Output of alpha:

![selection_229](https://cloud.githubusercontent.com/assets/8877333/8295882/c2f17ad6-190e-11e5-820d-d3063663c424.png)

**Comment by mojavelinux** [comment]
I'm pretty sure I fixed this in a recent commit. Regardless, you should be able to make the table opaque by setting the background color explicitly.

```
table:
  background_color: ffffff
```

**Comment by mojavelinux** [comment]
alpha.8 is out. Can you retest?

**Comment by rlopez133** [comment]
Didn't try it in alpha8, but tried it in the latest dev and still does it. Within the theme, background_color: ffffff already exists.

**Comment by mojavelinux** [comment]
I think our source trees are out of sync because I can't see how this can happen with the latest code. We specifically set the background color to white if no background color is specified on the table or the color is transparent.

**Comment by rlopez133** [comment]
I'm still seeing this behavior on alpha8. I'm testing this on a new system.

**Comment by mojavelinux** [comment]
Here's what I see with the latest dev using your theme.

![table-1](https://cloud.githubusercontent.com/assets/79351/8373486/8df111ae-1baa-11e5-887d-c6bfa8561e7c.png)

**Comment by mojavelinux** [comment]
One way to fix this for sure is to set explicitly set the odd row background color (even though I'm positive we are setting this value to white internally).

```
table:
  odd_row_background_color: ffffff
```

**Comment by rlopez133** [comment]
Just FYI, adding odd_row_background_color: fffff does work!

**Comment by mojavelinux** [comment]
I believe this was also resolved by df5f29c039108bf44e50e4c58fd9ac71a8decefc.
