### ISSUE TITLE
Can't properly render URLs due to unknown glyphs

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#795]
I'm linking to asciidoctor.org in my document. I'm using the TitilliumWeb font from Google for my template.

When I output the document I get error messages about non 1252 characters (see #794) but it also complains about the URLs. None of the other URLs in the document are affected by this.

The URLs are defined in the document like this:

```
==== Syntax

Die Grundlage für der Dokumente ist das AsciiDoc Format (link:http://asciidoctor.org/docs/what-is-asciidoc/[]). Es handelt sich um eine simple Syntaxsprache die es erlaubt mit einfachen Formatierungszeichen komplex strukturierte Dokumente zu erzeugen. Gleichzeitig ist das Format aber mächtig genug um nahezu alle Anforderungen an die Inhalte der Softwaredokumentation zu erfüllen. Das Format und die damit verbundenen Werkzeuge werden von einer aktiven Entwicklercommunity ständig weiter entwickelt.

Dabei bleibt alles in lesbarer Schreibweise in den Quelldokumenten erhalten so dass jeder Benutzer in kürzester Zeit alle Aspekte des Dokumentes verstehen und bearbeiten kann.

[TIP]
====
Das Format bietet eine riesige Bandbreite an Formatierungsoptionen und Möglichkeiten um die erzeugten Dokumente an seine Bedürfnisse anzupassen. Diese alle auch nur ansatzweise zu erklären würde den Rahmen dieses Dokumentes sprengen. Machen Sie sich einfach selbst ein Bild: http://asciidoctor.org/docs/user-manual/
```

Interestingly when I rewrite the URLs to look like this:

`link:http://asciidoctor.org/docs/what-is-asciidoc/[What Is AsciiDoc]`
and
`link:http://asciidoctor.org/docs/user-manual/[AsciiDoctor User Manual]`

It works fine and does not complain.

Why is it that only these URLs are interpreted incorrectly? I use several other URLs in the document and none of them gets rendered with the "not"-glyph.

![screenshot from 2017-03-31 19-42-12](https://cloud.githubusercontent.com/assets/4920542/24562347/ce732e50-164a-11e7-8343-085d1879fb79.png)
![screenshot from 2017-03-31 19-42-20](https://cloud.githubusercontent.com/assets/4920542/24562346/ce721b14-164a-11e7-88a7-dc47794e738c.png)

**Comment by mojavelinux** [comment]
> When I output the document I get error messages about non 1252 characters 

This is a clear indication you're using a built-in AFM font instead of a TTF font for your main text. You should almost never use the built-in AFM fonts.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#built-in-afm-fonts

The reason for the "not" glyph here is because we are inserting a "break" hint in raw URLs to allow them to be wrapped. The character we use is a zero-width space, which is not available when using an AFM font.

We could introduce an attribute to disable this behavior (or detect the use of the AFM font), but to be honest, you should not be using an AFM font with Asciidoctor PDF.

**Comment by mojavelinux** [comment]
Btw, this is not specific to Asciidoctor URLs. It has to do with whether the URL contains a break opportunity, which is essentially a forward slash.

**Comment by mojavelinux** [comment]
>  I'm using the TitilliumWeb font from Google for my template.

I'm not convinced you've configured it correctly. Do you have the following declaration?

```
base:
  font_family: TitilliumWeb
```

?

**Comment by mojavelinux** [comment]
It seems reasonable to me to detect whether the font supports zero-width space (in our case, as long as it's not an AFM font). The glyph does not need to be present in the non-AFM font as Prawn does not attempt to render the zero-width space glyph in that case.

There are some future edge cases where the font used to render the link could be different than the current font at the time the breakable logic is performed, so we may have to relocate the logic...but this is going to cover 99% of themes.

**Comment by mojavelinux** [comment]
It's interesting why this is a problem. Prawn encodes the string before it starts to render it. When the font is AFM, Prawn encodes to windows-1252. The zero-width space is not in the windows-1252 charset, so therefore it gets replaced with the not symbol. Prawn only looks for break opportunities at a zero-width space. But there's no way to have a windows-1252 encoded string w/ a zero-width space. So basically it is Prawn that prevents us from using the break hint feature when an AFM font is in use.

In the end, I'd argue that Prawn doesn't really work properly with AFM fonts (as some of its features get implicitly disabled).

**Comment by mojavelinux** [comment]
> There are some future edge cases where the font used to render the link could be different than the current font at the time the breakable logic is performed

I'm confident I have this covered now.

**Comment by mojavelinux** [comment]
The one exception is tables. I can't detect which font is used for tables from where we add break hints to URIs. This is just one of those places where the cart gets in front of the horse in Prawn.

**Comment by mojavelinux** [comment]
Okay, I found a better way to do this that covers all cases of using an AFM font. It even allows all built-in glyphs to work out of the box, such as markers on unordered lists and narrow spaces inside button brackets and around dashes. Basically, we're now making suitable substitution when converting to an AFM font. (I suppose we still could replace conums, but let's handle that in a separate issue).

**Comment by r0ckarong** [comment]
I have this configured for the use of the font. I am already a little confused as to how to define a document wide font in this way.

Font Catalog
```
font:
  catalog:
    # TitilliumWeb
    TitilliumWeb:
      normal: titilliumweb-normal.ttf
      bold: titilliumweb-bold.ttf
      italic: titilliumweb-italic.ttf
      bold-italic: titilliumweb-bold_italic.ttf
... More Fonts (Standard)
´´`
Brand style
´´´
brand:
  # font: Noto Serif
  font_family: TitilliumWeb
  aragoblue: #004481
  darkblue: #031c31
  lightgrey: #898989
  blue_gradient:
    start: #25b5ec
    end: #20ecff
  purple_gradient:
    start: #9524a6
    end: #ca98df
  orange_gradient:
    start: #ff7a20
    end: #ff9920
  red: #ee2957
  yellow: #e2ee29
  green: #47d05b
  darkred: #ba3925
```
base definition
```
base:
  align: justify
  # color as hex string (leading # is optional)
  font_color: 333333
  font_family: $brand_font
  font_size: 10
  line_height_length: 13.8
  line_height: $base_line_height_length / $base_font_size
  font_size_large: round($base_font_size * 1.25)
  font_size_small: round($base_font_size * 0.85)
  font_size_min: $base_font_size * 0.75
  font_style: normal
  border_color: #EEEEEE
  border_radius: 4
  border_width: 0.5
```

What I'm confused by is if I declare "font: TitilliumWeb" in the brand section the document will not pick up the change and falls back. If I do it with font_family it works.

**Comment by r0ckarong** [comment]
I forgot: Why this is so confusing is because when I set "font: TitilliumWeb" AsciiDoctor-PDF dies during processing saying "`initialize':  is not a known font. (Prawn::Errors::UnknownFont)" I looked at the code in Prawn at that place and from what I understand it should use the font name from there. For some reason that doesn't work.

```
/var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font/afm.rb:48:in `initialize':  is not a known font. (Prawn::Errors::UnknownFont)
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:289:in `new'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:289:in `load'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:243:in `find_font'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:57:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:192:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2923:in `theme_font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2145:in `block in layout_title_page'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2924:in `block in theme_font'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:62:in `block in font'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /var/lib/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:60:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:192:in `font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2923:in `theme_font'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2124:in `layout_title_page'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:187:in `convert_document'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:120:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:1050:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1506:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:23:in `load'
	from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by mojavelinux** [comment]
> What I'm confused by is if I declare "font: TitilliumWeb" in the brand section the document will not pick up the change and falls back. If I do it with font_family it works.

It should work either way. I don't understand why it's not working for you. Something else is going wrong there.

Asciidoctor PDF uses the name you specify for the font in the catalog to reference to font file. No other name is considered. You could name it "Aliens" if you wanted and that would work.

**Comment by mojavelinux** [comment]
> I am already a little confused as to how to define a document wide font in this way.

The document-wide font is base_font_family (which can be written in the nested style, of course). If no font is specific for a specific content type, such as the sidebar, this is the font that is used. If you don't specify a base_font_family, then Helvetica is used.

As I always recommend when debugging, start with the simplest possible thing and build from there. It's very difficult to debug when you have tons of variables.

**Comment by mojavelinux** [comment]
I'm assuming you are setting pdf-fontsdir as well, correct? To simplify things when testing, I'd actually recommend just using absolute paths for fonts until you have everything set the way you want, then switch to relative paths.

**Comment by r0ckarong** [comment]
Yes I'm passing pdf-fontsdir to asciidoctor-pdf as a parameter on the command line.

**Comment by r0ckarong** [comment]
OK so it turns out that I've been looking at Helvetica the whole time. Now I tried doing what you suggested and define my custom font as 

```
base:
  font_family: TitilliumWeb
```

This causes the error message above where it tries to "initialize" with an empty value for the font.
So far I haven't found a way to actually configure this to use the font and actually work.

Is there some way I can debug what it's doing to arrive at an empty value for the font name?

**Comment by mojavelinux** [comment]
The most efficient way to proceed is to create a sample project and push it
to GitHub. You can always delete it later. It's easier to share than
explain ;)

**Comment by r0ckarong** [comment]
I've created a very simple project here with my configuration:

https://github.com/r0ckarong/asciidoctor-pdf-debug

The theme is exactly what I'm using right now and thus breaks.

When I change brand_font_family to my custom font it will no longer produce the error but fall back to Helvetica. 

Funnily enough I mistyped the font as "TitlliumWeb" (missing an i) first and then it would give me an :error with that misspelled font:

```
/usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/afm.rb:48:in `initialize': TitlliumWeb is not a known font. (Prawn::Errors::UnknownFont)
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:289:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:289:in `load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:243:in `find_font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:57:in `font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:192:in `font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2923:in `theme_font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:2314:in `layout_toc'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:196:in `block in convert_document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:802:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:802:in `block in dry_run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:62:in `block in font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font.rb:60:in `font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:192:in `font'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/prawn_ext/extensions.rb:801:in `dry_run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:196:in `convert_document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/lib/asciidoctor-pdf/converter.rb:120:in `convert'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:1050:in `convert'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1506:in `convert'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.15/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
```

If you spell it correctly it gives me that error with an empty space as the unknown font name.

**Comment by r0ckarong** [comment]
Oh and I'm using asciidoctor-pdf-1.5.0.alpha.15 but that should be clear from the error messages.

**Comment by mojavelinux** [comment]
This was just a simple matter of typos in your theme. In some cases you used $brand_font and in others $brand_font_family. When an attribute doesn't resolve, it resolves to blank, which is why you were getting an empty name in the error message.

We should probably warn when a variable can't be resolved in the theme file.

**Comment by r0ckarong** [comment]
Now I've applied your fix to my larger project and I'm getting the "empty" error message again. What am I still doing wrong? The setup is exactly the same as with the demo project.

**Comment by mojavelinux** [comment]
I'm absolutely confident the problem is invalid variable names. I had never thought of this problem before since I was always creating themes that follow the happy path. I've opened an issue so that we get a warning in the future. That should definitely help with debugging. See #801.

**Comment by mojavelinux** [comment]
Did you manage to sort it out?

**Comment by r0ckarong** [comment]
Nope, see comment above. I used your changes and then it gives me the empty font name problem again.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by mojavelinux** [comment]
Yes, but did you check every `$` reference? One of them is not resolving...perhaps due to a typo. Can you put the exact theme file in that repository you shared with me?

**Comment by mojavelinux** [comment]
Basically, it's impossible (unless I'm missing something) to get an empty font name for any other reason than the variable is not resolving. Otherwise, you would see a value in the message.

**Comment by r0ckarong** [comment]
This is why I'm not getting it. The test project works. I get a correct document with the custom font. In my large project it doesn't.

I have now committed all the files as they are into the repo so you can check for yourself. 

Thanks a lot for your patience.

**Comment by mojavelinux** [comment]
Great! I'll have a look!

**Comment by mojavelinux** [comment]
You had three errors / typos.

1. You use the key bold-italic instead of bold_italic when defining the TitilliumWeb font, so it couldn't find the bold italic font when it needed it
2. You defined the title_page category before the base and heading, which is where many variables are defined; therefore, you had a few unresolved variable references and a few which actually used the wrong values
3. You defined the style for the h5 heading (h5_font_style) as bold-italic instead of bold_italic

(The first two would have be resolved by the new warning that's been introduced in the upcoming release).

You were correct that the error message from Prawn is incorrectly showing blank even when the font name is valid. That's what's happening in a third error. This is clearly a deficiency in Prawn. If the font family is valid, but the font style is invalid, it does not report the name of the font. I suppose we can be proactive and make sure the style is valid.

**Comment by r0ckarong** [comment]
Whew, you're my hero today. Unfortunately I already had to ship our the document yesterday with the fallback font but now this is finally resolved. It's been bugging me for months before I found the time trying to fix it.

1+3) I remember fixing this in one of my experiments but apparently I didn't fix it both in the heading style so it still broke and I reverted that. D'oh
2) Would this be something to include in the theming guide as a note? I assumed you'd parse all that stuff first and then resolve vars from that so I didn't bother trying to make sure stuff was declared in the proper order.

Does it make sense to file something with the prawn devs about this related error?

**Comment by mojavelinux** [comment]
I'm so glad to hear that!

> I remember fixing this in one of my experiments but apparently I didn't fix it both in the heading style so it still broke and I reverted that. D'oh

Don't worry, it took me quite a few tries to notice it as well. It was very subtle.

>  Would this be something to include in the theming guide as a note?

Yes. It's something I overlooked pointing out in the documentation...but it's definitely a rule. You can't reference a variable before it is defined. The variables are resolved top to bottom. I'll add this point.

> Does it make sense to file something with the prawn devs about this related error?

Yes, I think Prawn should report the original parameters of the font in the error message. Instead, it's reporting the resolved value, which ends up being blank when it can't find the style for a given font.

**Comment by mojavelinux** [comment]
I've updated the theming guide.

> Does it make sense to file something with the prawn devs about this related error?

We might be able to catch this error and provide a better error message in Asciidoctor PDF.
